import { ToolDefinition } from "@/types/tool";

export const tools: ToolDefinition[] = [
  // ===== APIFY ACTORS =====
  {
    id: "bamboo-employee-stats",
    name: "BambooHR Employee Stats",
    description:
      "Exports and analyzes employees from BambooHR. Downloads team data, generates statistics (per team/department/overall), and optionally writes to Google Sheets via an Apps Script web app. Salary report with raise recommendations is opt-in.",
    category: "hr-people",
    type: "apify",
    icon: "Users",
    tags: ["bamboohr", "employees", "hr", "statistics", "hierarchy"],
    status: "active",
    actorName: "bamboo-employee-stats",
    localPath: "c:/_PROJEKTY/bambboo-employe-stats",
    defaultInput: {
      subdomain: "apify",
      managerEmail: "vladimir@apify.com",
      hierarchyMode: true,
      onlyActive: true,
      includeSalaryReport: false,
      usdToCzkRate: 23.5,
      googleWebAppUrl: "",
    },
    outputConfig: {
      hasDataset: true,
      hasKvStore: true,
      kvCsvReportKey: "OUTPUT_CSV",
      externalOutputs: [{ label: "Google Sheets", type: "google-sheet" }],
    },
  },
  {
    id: "cr-reminder-2",
    name: "Code Review Reminder v2",
    description:
      "Scans open GitHub Pull Requests awaiting review and posts a compact, tagged reminder to Slack. Supports per-team filters (via repo topic), draft/blocked skipping, and severity thresholds (warning / scream).",
    category: "monitoring",
    type: "apify",
    icon: "Bell",
    tags: ["github", "slack", "code-review", "pull-requests", "reminder"],
    status: "active",
    actorName: "cr-reminder-2",
    localPath: "c:/_PROJEKTY/cr-reminder2",
    defaultInput: {
      githubOrg: "apify-store",
      githubTopic: "google-team",
      slackChannelId: "C01234567",
      userMapping: {},
      mode: "overdue",
      overdueThresholdDays: 3,
      warningThresholdDays: 3,
      screamThresholdDays: 7,
      sendEmptyReport: false,
      headerText: "Pull requests in review:",
      ignoreLabels: ["blocked"],
    },
    outputConfig: {
      hasDataset: true,
      hasKvStore: false,
      externalOutputs: [{ label: "Slack", type: "slack" }],
    },
  },
  {
    id: "github-sign-commits",
    name: "GitHub Commit Signing Checker",
    description:
      "Checks whether the last PR commit by each GitHub organization member is GPG/SSH-signed. Generates an interactive HTML report with filtering by org, signing status, and username.",
    category: "security",
    type: "apify",
    icon: "ShieldCheck",
    tags: ["github", "gpg", "signing", "security", "compliance"],
    status: "active",
    actorName: "github-sign-commits",
    localPath: "c:/_PROJEKTY/github-sign-commits",
    defaultInput: {
      organizations: ["apify-store", "apify-projects"],
      teams: [
        "apify-store/store-engineering",
        "apify-projects/professional-services",
        "apify-store/store-pms",
      ],
      recursiveTeams: true,
      ignoreUsernames: [],
      includePrivateRepos: false,
    },
    outputConfig: {
      hasDataset: true,
      hasKvStore: true,
      kvHtmlReportKey: "report",
    },
  },
  {
    id: "github-user-report",
    name: "GitHub Developer Activity Report",
    description:
      "Analyzes GitHub developer activity (commits, PRs, reviews, response/merge times) and generates an interactive HTML report with charts, team comparisons, and per-developer metrics.",
    category: "github-analysis",
    type: "apify",
    icon: "TrendingUp",
    tags: ["github", "developers", "activity", "performance", "report"],
    status: "active",
    actorName: "github-user-report",
    localPath: "c:/_PROJEKTY/github-user-report",
    defaultInput: {
      organizations: ["apify-store", "apify-projects"],
      teams: ["apify-store/store-engineering"],
      recursiveTeams: true,
      ignoreUsernames: [],
      periodDays: 90,
    },
    outputConfig: {
      hasDataset: true,
      hasKvStore: true,
      kvHtmlReportKey: "report",
    },
  },
  {
    id: "zenhub-sprint-report",
    name: "ZenHub Sprint Report",
    description:
      "Fetches ZenHub sprint data via the GraphQL API for multiple workspaces and produces an interactive HTML report plus a JSON dataset. Tracks sprint velocity, bug counts, and label distribution.",
    category: "monitoring",
    type: "apify",
    icon: "TrendingUp",
    tags: ["zenhub", "sprint", "report", "velocity", "agile"],
    status: "active",
    actorName: "zenhub-sprint-report",
    localPath: "c:/_PROJEKTY/zenhub-sprint-report",
    defaultInput: {
      workspaces: [
        { workspaceId: "664c8d5e1069c6029cc683c1", teamName: "Google Team" },
        { workspaceId: "664c90646b2c313433013fe3", teamName: "Video Team" },
        { workspaceId: "664f250049eeb60030e3b29e", teamName: "Socials Team" },
      ],
      sprintCount: 10,
      bugLabels: ["bug"],
      ignoreLabels: ["zenhub:"],
    },
    outputConfig: {
      hasDataset: true,
      hasKvStore: true,
      kvHtmlReportKey: "report",
    },
  },
];
